name: qr_angulardart
version: 0.1.0
description: >-
  QR.AngularDart is an AngularDart component to easily show a QR code.
homepage: https://github.com/gazialankus/qr.angulardart/

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.0
  qr: ^1.2.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: '>=1.1.0 <3.0.0'
  pedantic: ^1.0.0
  stream_transform: ^0.0.20
  test: ^1.5.0
